Avoid copies when passing binary parameters
haskellari/postgresql-libpq pull request #22
Opened 2022-06-30 10:27 UTC by robx

Currently, the library copies every input parameter when passing it to libpq via `Data.ByteString.useAsCString`. This PR avoids those copies for the case of binary parameters, by using `Data.ByteString.Unsafe.unsafeUseAsCString`.

I claim that this is safe because:
- libpq doesn't require binary parameters to be zero-terminated, they are passed with length
- libpq treats parameter input as read-only
- `ByteString` uses pinned memory

There are a few preparatory commits to factor out duplicate code to `withParams`, and to avoid a bit of unnecessary work there.

Context is https://github.com/PostgREST/postgrest/issues/2261. We see significant decrease of memory use with this change: https://github.com/PostgREST/postgrest/pull/2349

2022-07-03 18:39 UTC, phadej requested changes
This PR does multiple things at once. Please split.

2022-07-04 08:21 UTC, robx commented
I've split out the first commit in #23, will file follow-up PRs if/as that one gets merged.

2022-07-04 08:22 UTC, robx commented
Apologies for the re-review request, meant to request review for #23.

2022-07-20 08:41 UTC, robx commented
> This PR does multiple things at once. Please split.

Did you see #23? Is that what you had in mind?

2022-09-05 13:34 UTC, phadej commented
Please reread https://github.com/haskellari/postgresql-libpq/blob/master/CONTRIBUTING.md

2022-09-05 13:39 UTC, robx commented
Sorry, that's because I was repurposing the branch to file a PR against a fork of this repo. Closing.

2022-09-05 13:39 UTC, closed without merging

2022-09-05 14:07 UTC, phadej commented
fork? interesting...